config/routes.rb
Brainforest::Application.routes.draw do

  root "products#index"

  resources :products do
    resources :reviews, :except => [:index]
  end
  
  resources :users, :only => [:new, :create, :show]
  resources :sessions, :only => [:new, :create, :destroy]
  

  

end

app/models/product.rb
class Product < ActiveRecord::Base

	mount_uploader :image1, ProductImageUploader
	mount_uploader :image2, ProductImageUploader
	mount_uploader :image3, ProductImageUploader
	mount_uploader :image4, ProductImageUploader
	mount_uploader :image5, ProductImageUploader

	belongs_to :user

	has_many :reviews
	has_many :users, :through => :reviews

	has_many :images

	validates :description, :name, :presence => true
	validates :price_in_cents, :numericality => {:only_integer => true, :greater_than => 0}

	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		sprintf("%.2f",price_in_dollars)
	end

	def average_rating
		rsum = self.reviews.sum(:rating)
		rcount = self.reviews.count
		average = rsum/rcount.to_f
		sprintf("%.1f",average *= 100)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :product
	belongs_to :user

	# before_validation :make_price_an_integer

	validates :comment, :rating, :presence => true
	#validates :price_in_cents, :numericality => {:only_integer}


end

app/models/user.rb
class User < ActiveRecord::Base

	mount_uploader :avatar, AvatarUploader

	#require 'carrierwave/orm/activerecord'

has_secure_password
	validates_presence_of :password, :on => :create
	#automatically creates  :password, :password_confirmation

	has_many :reviews
	has_many :products, :through => :reviews

	validates :nick, :email, :presence => true
	validates_uniqueness_of :nick, :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "You must be logged in"
  		redirect_to new_session_path
  	end
  end

  helper_method :current_user

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter  :ensure_logged_in, :only => [:create, :edit, :update, :destroy]

  def index
  	@products = Product.all
  end

  def show
  	@product = Product.find(params[:id])

  	if current_user
      @review = Review.new
  	end
  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params)
    @product.user_id = current_user.id
  	if @product.save
  		redirect_to products_url
  	else
  		render :new
  	end
  end

  def update
  	@product = Product.find(params[:id])

  	if @product.update_attributes(product_params)
  		redirect_to product_path(@product)
  	else
  		render :edit
  	end
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
  	redirect_to products_path
  end

  def product_params
    params.require(:product).permit( :name, :description, :price_in_cents, :rating, :user_id, :image1, :image2, :image3, :image4, :image5, :remove_image1, :remove_image2, :remove_image3, :remove_image4, :remove_image5,)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :ensure_logged_in, :only => [:edit, :create, :update, :destroy]

	before_filter :load_product

  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user_id = current_user.id

    sleep(1)

    respond_to do |format|
    	if @review.save
    		format.html{ redirect_to product_path(params[:id]), notice: 'Review posted!'}
        format.js {} # This will look for app/views/reviews/create.js.erb
        # format.json { @review } to return as a json object
    	else
    		format.html{ render :action => :show }
        format.js {} # This will look for app/views/reviews/create.js.erb
    	end
    end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
    redirect_to product_path(params[:product_id]), notice: 'Review deleted.'
  end

  def edit
  end

  private

  def load_product
  	@product = Product.find(params[:product_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	# To create a log in, there is no need to instantiate a new 'session' by creating a new instance. 
	# When we hit the 'submit' button, our create action is triggered.
	def new
  end

  def create
  	user = User.find_by_email(params[:email]) # find a user by the email typed in the email input field and assign it to the variable 'user'
  	if user && user.authenticate(params[:password]) # check if that user exists and that it can be authenticated with the password typed in the password input field
  		session[:user_id] = user.id #RAILS MAGIC: create a key-value pair in the session hash. ':user_id' is the key and the user's id is the value
  		redirect_to products_url, :notice => "Welcome, #{user.nick}"
  	else
  		flash.now[:alert] = "Invalid email or password"
  		render "new"
  	end
  end
		# This gist of logging in is that we are setting a hash in our users' browser to let our server (application) 
 		# reference as they navigate through the application.

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, :notice => "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      session[:user_id] = @user.id
  		redirect_to products_path, :notice => "Account Created!"
  	else
  		render "new"
  	end
  end

  def show
    @user = User.find(current_user.id)
  end

private
	def user_params
    params.require(:user).permit(:nick, :email, :password, :password_confirmation, :avatar )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brainforest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id = "container">
	<div id = "header">
		<h1><%= link_to "brainforest", products_path %></h1>
		<div id = "user_panel">
			<% if current_user %>
				<%= link_to current_user.nick, user_path(current_user.id) %> | <%= link_to "Logout", session_path("current"), :method => :delete %>
			<% else %>
				<%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
			<% end  %>
		</div>
	</div>
	<div id = "alert_space">
		<% if flash[:notice] %>
			<p id = "notice">
				<%= flash[:notice] %>
			</p>
		<% end %>
		<% if flash[:alert] %>
			<p id = "alert">
				<%= flash[:alert] %>
			</p>
	<% end %>
	</div>

	<div id = "main">
		<%= yield %>
	</div>
</div>

</body>
</html>

app/views/products/_image_controls.html.erb
<%  if @product.user_id == current_user.id %>
	<%= link_to "remove image", @product.remove_image1! %>
<% end %>

app/views/products/_product_form.html.erb
<%= form_for @product do |f| %>
	<% if @product.errors.any? %>
		<div id = "product_form_error">
			<h3>Can't save due to <%= pluralize(@product.errors.count, "error") %></h3>
			<ul>
				<% @product.errors.full_messages.each do |error_message| %>
					<li><%= error_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class = "field" >
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class = "field" >
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>
	<div class = "field" >
		<%= f.label :price_in_cents %>
		<%= f.text_field :price_in_cents %>
	</div>
	<div class = "field">
		<%= f.label :image %>
		<%= f.file_field :image1 %>
	</div>
	<div class = "actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/products/_product_images.html.erb
	<div class = "image">
	<%= link_to image_tag(@product.image1), @product.image1.url %>
	</div>
	<% if @product.image2? %>
		<div class = "image">
		<%= link_to image_tag(@product.image2), @product.image2.url %>
		</div>
	<% end  %>
	<% if @product.image3?  %>
		<div class = "image">
		<%= link_to image_tag(@product.image3), @product.image3.url %>
		</div>
	<% end  %>
	<% if @product.image4? %>
		<div class = "image">
		<%= link_to image_tag(@product.image4), @product.image4.url %>
		</div>
	<% end  %>
	<% if @product.image5?  %>
		<div class = "image">
		<%= link_to image_tag(@product.image5), @product.image5.url %>
		</div>
	<% end  %>

app/views/products/_review_form.html.erb
<%= form_for([@product, @review], :remote => true) do |f| %>
<div class = "newreview"> 
<% if @review.errors.any?  %>
	<div id = "error_explanation">
		<ul>
			<%= @review.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end  %>


<div class = "field">
	<%= f.text_area :comment, :size => "60x4" %>
</div>
<div class = "radio_field">
	<%= f.radio_button :rating, -1 %>
	<%= f.label :rating_dislike, "Dislike" %>
	<%= f.radio_button :rating, 0 %>
	<%= f.label :rating_indifferent, "Indifferent" %>
	<%= f.radio_button :rating, 1 %>
	<%= f.label :rating_like, "Like" %>
</div>
<div class = "actions"> 
	<%= f.submit %> 
</div>
</div>
<% end  %>

<script type="text/javascript">
	$('form')
	.on('ajax:beforeSend',function(){ $("input[type='submit']").val("Saving...").attr('disabled','disabled');})
	.on('ajax:complete',function(){ $("input[type='submit']").val("Submit").removeAttr('disabled');})
</script>

app/views/products/_reviews.html.erb
<h5>Reviews for <%= @product.name %></h5>
<% if @product.reviews.count > 0 %>
	<% @product.reviews.reverse.each do |review|  %>
		<div class = "review">
			<p class = "reviewtext"> <%= review.comment %> </p>
			<br>
			<p> rated : <%= review.rating %> </p>
			<% if review.user != nil  %>
				<p> by <strong> <%= review.user.nick %></strong> on <em> <%= review.created_at %></em> </p> 
				<% if review.user_id == current_user.id %>
					<p> <%= link_to "[x]", product_review_path(@product.id, review.id), :method => :delete %></p>
				<% end  %>		
			<% end  %>	
			</div>
	<% end %>
<% else %>
		<em> no reviews yet! </em>
<% end  %>

app/views/products/edit.html.erb
<h3>edit product</h3>
<%= form_for @product, :html => {:multipart => true} do |f| %>
	<% if @product.errors.any? %>
		<div id = "product_form_error">
			<h3>Can't save due to <%= pluralize(@product.errors.count, "error") %></h3>
			<ul>
				<% @product.errors.full_messages.each do |error_message| %>
					<li><%= error_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class = "image_gallery">
		<div class = "five_image_container">
			<div class = "edit_image">
				<%= link_to image_tag(@product.image1), @product.image1.url %>
					<p><%= f.file_field :image1 %><p>
			</div>

			<div class = "edit_image">
				<%= link_to image_tag(@product.image2), @product.image2.url %>
					<p><%= f.file_field :image2 %><p>	
    			
			</div>

			<div class = "edit_image">
				<%= link_to image_tag(@product.image3), @product.image3.url %>
					<p><%= f.file_field :image3 %><p>	
			</div>

			<div class = "edit_image">
				<%= link_to image_tag(@product.image4), @product.image4.url%>
					<p><%= f.file_field :image4 %><p>	
			</div>

			<div class = "edit_image">
				<%= link_to image_tag(@product.image5), @product.image5.url %>
					<p><%= f.file_field :image5 %><p>	
			</div>
		</div>
	</div>
	<div class = "field" >
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class = "field" >
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div>
	<div class = "field" >
		<%= f.label :price_in_cents %>
		<%= f.text_field :price_in_cents %>
	</div>
	<div class = "actions">
		<%= f.submit %>
	</div>
<% end %>

<%= link_to 'Back', product_path %>

app/views/products/index.html.erb
<h3>all products</h3>

<div class = "all_products">
<ol>
	<% @products.each do |product| %>
	<li><%= link_to product[:name], "/products/#{product.id}" %></li>
	<% end %>
</ol>
</div>

<p>
	<%= link_to "New Product", new_product_url %>
<p>

app/views/products/new.html.erb
<h2> New product </h2>
<%= render 'product_form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class = "product_info">
	<div class = "image_gallery">
		<div class = "five_image_container">
			<%= render "product_images" %>
		</div>
	</div>
	<h4><%= @product[:name] %></h4>
	<p><%= @product[:description] %></p>
	<p>$<%= @product.formatted_price %></p>
	<p>by <em><%= User.find(@product.user_id).nick %></em></p> 
	<% if current_user %>
		<%  if @product.user_id == current_user.id %>
			<p> <%= link_to "[x]", @product, :method => :delete %>
			<%= link_to "[e]", edit_product_url %></p>
		<%  end  %>
	<% end  %>
</div>
<% unless current_user %>
<p><em>Log in to read and post reviews</em><p>
<% end %>

<div class = "rating">
	<% if @product.reviews.count > 2 %>
	average approval: <%= @product.average_rating %>%
	<% end %>
</div>

<% if current_user %>
<div class = "reviews">
	<%= render "reviews" %> 
</div>
	<%= render "review_form" %> 
<% end %>

<p>
	<%= link_to "Index", products_url %>
</p>

app/views/products/show.js.erb
$('body').append("<%= escape_javascript(render @product) %>");

app/views/reviews/create.js.erb
alert("ajax called now")
$('.reviews').html("<%= escape_javascript(render(:partial => 'products/reviews'))  %>");
$('.field')[0].reset();

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

<%= render "review_form" %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class = "error_message">
			<h2>Error</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class = "field">
		<%= f.label :avatar %>
		<%= f.file_field :avatar %>
	</div>
	<div class = "field">
		<%= f.label :nickname %>
		<%= f.text_field :nick %>
	</div>
	<div class = "field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div class = "field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div class = "field">
		<%= f.label :confirm %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class = "actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h2> new luser </h2>

<%= render "user_form" %>

<%= link_to "Home", root_url %>

app/views/users/show.html.erb
<div class = "user_info">
	<% if current_user %>
<h4><%= @user[:nick] %>'s profile</h4>
<img src ="<%= @user.avatar %>" alt ="AVATAR">
<% end %>

<p>
	<%= link_to "Index", products_url %>
</p>